project:
  type: website
  output-dir: docs

website:
  title: "Dianne Yumol"
  navbar:
    left:
      - href: index.qmd
        text: About
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true